// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVqocC_DD9kBdW-41ccOFc4B51eOw4ofU',
    appId: '1:570301401734:web:b788f9cc9b781b26f21f07',
    messagingSenderId: '570301401734',
    projectId: 'trive-ntp',
    authDomain: 'trive-ntp.firebaseapp.com',
    storageBucket: 'trive-ntp.appspot.com',
    measurementId: 'G-JD8QSC610P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi9OI3PpmGRvfntcE3urdtbjEIOrgPeZU',
    appId: '1:570301401734:android:bebcace6cfaa5757f21f07',
    messagingSenderId: '570301401734',
    projectId: 'trive-ntp',
    storageBucket: 'trive-ntp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnR-CbW3cKJBWYmpECztqF8ySs3n3u-54',
    appId: '1:570301401734:ios:0839135153b0709cf21f07',
    messagingSenderId: '570301401734',
    projectId: 'trive-ntp',
    storageBucket: 'trive-ntp.appspot.com',
    iosBundleId: 'com.example.triveBysc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnR-CbW3cKJBWYmpECztqF8ySs3n3u-54',
    appId: '1:570301401734:ios:0839135153b0709cf21f07',
    messagingSenderId: '570301401734',
    projectId: 'trive-ntp',
    storageBucket: 'trive-ntp.appspot.com',
    iosBundleId: 'com.example.triveBysc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVqocC_DD9kBdW-41ccOFc4B51eOw4ofU',
    appId: '1:570301401734:web:458f9efbf2238afbf21f07',
    messagingSenderId: '570301401734',
    projectId: 'trive-ntp',
    authDomain: 'trive-ntp.firebaseapp.com',
    storageBucket: 'trive-ntp.appspot.com',
    measurementId: 'G-X61TQVSYMM',
  );

}