// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGYMjhogjMWZ4CDFG6TaX_tToBFUgc4z8',
    appId: '1:723894435181:web:365b15a30a822a7156ae64',
    messagingSenderId: '723894435181',
    projectId: 'trive-4e1b7',
    authDomain: 'trive-4e1b7.firebaseapp.com',
    storageBucket: 'trive-4e1b7.appspot.com',
    measurementId: 'G-EBYSWY2K3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCiGQDPN93TAPHjBJREQ4X6TYk3CV6Z0E',
    appId: '1:723894435181:android:d98a42738460c7a556ae64',
    messagingSenderId: '723894435181',
    projectId: 'trive-4e1b7',
    storageBucket: 'trive-4e1b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRk2rdLmNT23h03NglH0ZUtk3URSX-MUM',
    appId: '1:723894435181:ios:7588c8e2320823a656ae64',
    messagingSenderId: '723894435181',
    projectId: 'trive-4e1b7',
    storageBucket: 'trive-4e1b7.appspot.com',
    iosClientId: '723894435181-kn4jp2nqbmu6ivrj800j8g161go1jtmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.triveBysc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRk2rdLmNT23h03NglH0ZUtk3URSX-MUM',
    appId: '1:723894435181:ios:63d751ac21b5798456ae64',
    messagingSenderId: '723894435181',
    projectId: 'trive-4e1b7',
    storageBucket: 'trive-4e1b7.appspot.com',
    iosClientId: '723894435181-4slo7k1o7did9gavb6den16otc2cqan2.apps.googleusercontent.com',
    iosBundleId: 'com.example.triveBysc.RunnerTests',
  );
}
